import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const portSans = localFont({
  src:'./fonts/porter-sans-inline-block.ttf',
  display:'swap',
  variable: '--font-port-sans'
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${portSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
